module.exports = {
	channels: [],
	channelsById: {},
	createChannelError: false,
	isCreatingChannel: false,
	isDrawerOpen: false,
	isFetchingChannel: false,
	isFetchingChannels: false,
	isFetchingMessages: false,
	isLoggingIn: true,
	isRegistering: false,
	loginError: false,
	messagesByChannelId: {},
	registerError: false,
	user: null,
	users: [],
	...window.__INITIAL_STATE__,
}
