module.exports = {
	channelsById: {},
	createChannelError: false,
	isCreatingChannel: false,
	isDrawerOpen: false,
	isFetchingChannel: true,
	isFetchingChannels: false,
	isFetchingMessages: false,
	isFetchingUserMessages: false,
	isFetchingUser: false,
	isLoggingIn: true,
	isRegistering: false,
	loginError: false,
	messagesByChannelId: {},
	messagesByRecipientUserId: {},
	registerError: false,
	user: null,
	usersById: [],
	...window.__INITIAL_STATE__,
}
